id: 1adcc3e92a564a24bd39b2db9c37170f
initial_creation_type: ocr
source_metadata:
  volumes:
    cf71e0b794d04679b7d91f8cd9398118:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དཀོན་མཆོག་གསུམ་གྱི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
