id: D0A6044D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:11:45+00:00'
last_modified: '2022-05-26T06:09:02.413388+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '7078':
      image_group_id: I1PD95846
      title: དཀོན་མཆོག་གསུམ་གྱི་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: 7078.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
